# Generated by Django 2.2.4 on 2020-06-14 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiledetails', '0002_auto_20200614_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Info', to=settings.AUTH_USER_MODEL),
        ),
    ]
