# Generated by Django 2.2.4 on 2020-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledetails', '0005_auto_20200614_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cloudinary_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
