# Generated by Django 2.2.4 on 2020-06-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiledetails', '0006_auto_20200617_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_id', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
